version: "3"

services:
  #
  # Infrastructure
  #
  zookeeper:
    image: zookeeper:latest
    restart: "on-failure"
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    image: wurstmeister/kafka
    restart: "on-failure"
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  #
  # App
  #
  orwell:
    build: .
    environment:
      - ORWELL_KAFKA_BROKERS=kafka:9092
    ports:
      - "4000:4000"
    depends_on:
      - kafka
